### ISSUE TITLE
Finish Packager Settings form

### ISSUE THREAD

**Issue by paulbreuler** [paulbreuler/SolutionAssistant#1]
# TO-DO:

- [x] Add remaining CustomSelect components
- [x] Update CustomInput to allow state lifting
- [x] Add CustomInput controls needed to form
- [x] Generic redux state function implemented should be able to handle all updates with no additional code. (Completed)
- [x] Add error handling to make debugging easier ( Partially completed)

**Comment by SudoSandwichX** [comment]
# Updates
- Split solution name and path into two fields allowing a user to specify a file path for unpacking and allow setting name independent of the file path.
- Solution card now dynamically responds to packager settings
- Added field highlighting for the folder field in packager settings.

# Action Items
- [ ] Add notification if the user attempts to pack a solution without specifying Folder
    - [ ] Add similar check on solution card fields
- [ ] Add tooltips to fields. 
    - Had issues with build in tooltip for material-ui not playing well with tab container.
